export const createPermissionDto = [
    { "name": "Create Category" },
    { "name": "View Category" },
    { "name": "Update Category" },
    { "name": "Delete Category" },
    { "name": "Create Product" },
    { "name": "View Product" },
    { "name": "Update Product" },
    { "name": "Delete Product" },
    { "name": "Create Role" },
    { "name": "View Role" },
    { "name": "Update Role" },
    { "name": "Delete Role" },
    { "name": "Create Reception Order" },
    { "name": "View Reception Order" },
    { "name": "Update Reception Order" },
    { "name": "Delete Reception Order" },
    { "name": "Create Takeaway Order" },
    { "name": "View Takeaway Order" },
    { "name": "Update Takeaway Order" },
    { "name": "Delete Takeaway Order" },
    { "name": "Create Table Order" },
    { "name": "View Table Order" },
    { "name": "Update Table Order" },
    { "name": "Delete Table Order" },
    { "name": "Create Table" },
    { "name": "View Table" },
    { "name": "Update Table" },
    { "name": "Delete Table" },
    { "name": "Create Staff" },
    { "name": "View Staff" },
    { "name": "Update Staff" },
    { "name": "Delete Staff" },
    { "name": "View Statistics" }
];
